### ISSUE TITLE
Option to turn off blockquote max length

### ISSUE THREAD

**Issue by DhruvaSambrani** [LukeEmmet/html2gemini#9]
Please provide an option to turn off blockquote max length as breaks the quote into 2 lines unnecessarily.

**Comment by LukeEmmet** [comment]
I [removed ](https://github.com/LukeEmmet/html2gemini/commit/7a5e0baec07ac84fc4731f6e77529d7aad1d46bf)the legacy code that was breaking blockquotes up into smaller lines. So this should work better now
